using System.Text.Json;
using WayfarerRecovery;

namespace WayfarerCtl;

/// <summary>Administrator-facing restore coordination; archive integrity never implies authorization.</summary>
public sealed class RestoreCommands(IProcessRunner runner, ITerminal terminal)
{
    /// <summary>Plan before mutation, acquire locks in host/recovery order, and retain truthful durable failure phase.</summary>
    public async Task<int> RunAsync(string root, string[] args, CancellationToken token)
    {
        var options = RestoreOptions.Parse(args);
        ProtectedFiles.SafePath(root);
        if (!Directory.Exists(root)) Directory.CreateDirectory(root, ProtectedFiles.PrivateDirectory);
        ProtectedFiles.Check(root, 0, directory: true);
        using var operation = Setup.Lock(root);
        await new Preflight(runner).DockerAsync(token);
        if (options.Has("--resume") || options.Has("--abort")) return await RecoverAsync(root, options, token);
        RestoreReceipt.RequireResolved(root);
        RestorePlan plan;
        if (options.Has("--accept-plan")) plan = LoadPlan(root, options.Get("--accept-plan"));
        else
        {
            var config = options.Has("--new-install") ? NewTarget(root, options) : Deployment.Load(root);
            if (!options.Has("--new-install") && !InstallationCompletion.IsComplete(root)) throw new UsageException("Restore requires a completed installation.");
            if (options.Has("--new-install"))
            {
                await new Preflight(runner).FreshAsync(config, token);
                await new Preflight(runner).BundleAsync(root, config, token);
            }
            plan = await new RestorePreparation(runner).PrepareAsync(root, config, options, token);
        }
        terminal.Write(JsonSerializer.Serialize(plan));
        terminal.Write("Plan SHA-256: " + plan.Hash() + "\nLater writes will be discarded. Candidate writer launch is the rollback cutoff.");
        if (options.Has("--plan")) return 0;
        if (!options.Has("--trust-controlled-backup"))
            throw new UsageException("Explicit --trust-controlled-backup provenance acknowledgement is required before SQL execution.");
        if (!options.Has("--accept-plan"))
        {
            if (!terminal.Interactive) throw new UsageException("Redirected execution requires --accept-plan SHA256.");
            var expected = $"RESTORE {plan.Target.Installation:D} {plan.Archive:D}";
            if (terminal.Read("Type " + expected + ": ") != expected) { terminal.Write("Restore cancelled; authoritative state unchanged."); return 1; }
        }
        await RevalidateAsync(root, plan, token);
        if (plan.NewInstall)
        {
            ProtectedFiles.Create(Path.Combine(root, "installation.json"), JsonSerializer.Serialize(plan.Target));
            ProtectedFiles.CreateSecrets(root);
            ProtectedFiles.Create(Path.Combine(root, "deployment.env"), plan.Target.EnvironmentFile(root));
        }
        BackupConfiguration.ProvisionControl(root, true);
        var receipt = new RestoreReceipt { Plan = plan, PlanHash = plan.Hash() };
        using (var exclusion = new RecoveryLock(Path.Combine(root, "recovery-control/recovery.lock")))
        {
            if (File.Exists(Path.Combine(root, "recovery-control/host-operation.json"))) throw new IOException("Active recovery reservation.");
            receipt.Save(root);
        }
        return await ExecuteAsync(root, receipt, token);
    }

    /// <summary>Clean-root restoration reuses setup choices and preflight without invoking setup stages.</summary>
    private Deployment NewTarget(string root, RestoreOptions options)
    {
        if (File.Exists(Path.Combine(root, "installation.json")) || Directory.Exists(Path.Combine(root, "secrets")))
            throw new UsageException("New-install restore requires a clean target.");
        var config = new Setup(runner, terminal).ReadChoices(options.Values) with
        {
            Schema = 2, Installation = Guid.NewGuid(), DbDigest = options.Get("--db-digest")
        };
        config.CheckBundle();
        return config;
    }

    /// <summary>Only protected plans generated by this operator can supply target UUID or candidate generation.</summary>
    private static RestorePlan LoadPlan(string root, string hash)
    {
        var parent = Path.Combine(root, "restore-plans");
        foreach (var directory in Directory.EnumerateDirectories(parent).Take(101))
        {
            var path = Path.Combine(directory, "plan.json");
            if (!File.Exists(path)) continue;
            ProtectedFiles.SafePath(path);
            ProtectedFiles.Check(path, 0);
            if (new FileInfo(path).Length > 262144) throw new UsageException("Plan exceeds bound.");
            var plan = JsonSerializer.Deserialize<RestorePlan>(File.ReadAllText(path), ArchiveContract.Json);
            if (plan is not null && plan.Root == root && plan.Hash() == hash) return plan;
        }
        throw new UsageException("No matching protected restore plan.");
    }

    /// <summary>Bind execution to unchanged target authority and reverify only frozen bytes after interruption.</summary>
    private async Task RevalidateAsync(string root, RestorePlan plan, CancellationToken token)
    {
        if (plan.NewInstall)
        {
            if (File.Exists(Path.Combine(root, "installation.json")) || Directory.Exists(Path.Combine(root, "secrets")))
                throw new UsageException("Clean target changed since planning.");
            await new Preflight(runner).FreshAsync(plan.Target, token);
        }
        else if (JsonSerializer.Serialize(Deployment.Load(root)) != JsonSerializer.Serialize(plan.Target))
            throw new UsageException("Installation changed since planning.");
        var directory = RestorePreparation.DirectoryFor(root, plan.Operation);
        var payload = File.ReadAllText(Path.Combine(directory, "payload"));
        if (BackupPolicy.Fingerprint(payload) != plan.RestorePayloadFingerprint ||
            BackupConfiguration.BundleFingerprint(plan.Target) != plan.BundleFingerprint) throw new UsageException("Trusted payload/bundle changed.");
        var name = ArchiveContract.Name(plan.SourceInstallation, plan.Captured, plan.Archive);
        using var frozen = new SafeDirectory(Path.Combine(directory, "frozen"));
        using var archive = frozen.Read(name);
        if (Convert.ToHexStringLower(await System.Security.Cryptography.SHA256.HashDataAsync(archive, token)) != plan.ArchiveSha256)
            throw new UsageException("Frozen archive changed.");
        await new RestorePreparation(runner).VerifyAsync(plan.Target, directory, plan.Operation, payload, name, plan.SourceInstallation, token);
    }

    /// <summary>Emergency capture delegates to the existing lock-taking worker while host serialization and intent remain held.</summary>
    private async Task<int> ExecuteAsync(string root, RestoreReceipt receipt, CancellationToken token)
    {
        try
        {
            using (var exclusion = new RecoveryLock(Path.Combine(root, "recovery-control/recovery.lock")))
            {
                receipt = await new RestoreFencing(runner).FenceAsync(root, receipt, token);
                receipt = receipt.Advance(RestorePhase.Fenced);
                receipt.Save(root);
            }
            if (!receipt.Plan.NewInstall && !receipt.Plan.WithoutEmergencyBackup)
            {
                var capture = new BackupCommands(runner, terminal);
                if (await capture.RunAsync(root, receipt.Plan.Target, ["backup", "--quiesced"], token, restoreEmergency: true) != 0 || capture.CompletedArchive is null)
                    throw new IOException("Fresh emergency capture failed.");
                receipt = receipt with { EmergencyArchive = capture.CompletedArchive };
            }
            using var recovery = new RecoveryLock(Path.Combine(root, "recovery-control/recovery.lock"));
            receipt = receipt.Advance(RestorePhase.EmergencyVerifiedOrWaived);
            receipt.Save(root);
            await new RestoreFencing(runner).StopOwnedAsync(receipt, token);
            receipt = receipt.Advance(RestorePhase.Staging);
            receipt.Save(root);
            receipt = await new RestoreCandidate(runner).StageAsync(root, receipt, token);
            receipt = receipt.Advance(RestorePhase.CandidateValidated);
            receipt.Save(root);
            receipt = await new RestoreActivation(runner).ActivateAsync(root, receipt, token);
            terminal.Write($"Restore accepted: {receipt.Plan.Operation:D}. Old volumes and emergency evidence retained.");
            return 0;
        }
        catch
        {
            receipt = RestoreReceipt.Load(root) ?? receipt;
            using var cleanup = new CancellationTokenSource(TimeSpan.FromSeconds(60));
            try { await new RestoreFencing(runner).StopOwnedAsync(receipt, cleanup.Token); }
            catch { terminal.Error("Restore cleanup uncertain; durable intent retained."); }
            terminal.Error($"Restore incomplete: {receipt.Plan.Operation:D}; phase={receipt.Phase}; writes-possible={receipt.WritesPossible}. Installation remains fenced.");
            return 1;
        }
    }

    /// <summary>Recovery operates only on exact protected intent; no writer-cutoff rollback is inferred.</summary>
    private async Task<int> RecoverAsync(string root, RestoreOptions options, CancellationToken token)
    {
        var receipt = RestoreReceipt.Load(root) ?? throw new UsageException("No restore receipt.");
        var id = options.Get(options.Has("--abort") ? "--abort" : "--resume");
        if (receipt.Plan.Operation.ToString("D") != id) throw new UsageException("Restore operation mismatch.");
        using var recovery = new RecoveryLock(Path.Combine(root, "recovery-control/recovery.lock"));
        await new RestoreFencing(runner).StopOwnedAsync(receipt, token);
        if (options.Has("--abort"))
        {
            if (receipt.WritesPossible) throw new UsageException("Writes may have occurred; explicit recovery is required.");
            if (receipt.Phase >= RestorePhase.ActivationIntent)
            {
                if (receipt.OldConfiguration is null) throw new IOException("Previous authority unavailable.");
                var old = JsonSerializer.Deserialize<Deployment>(receipt.OldConfiguration)!;
                if (old.StorageGeneration is null)
                {
                    var path = Path.Combine(root, "installation.json.abort");
                    ProtectedFiles.Create(path, receipt.OldConfiguration);
                    File.Move(path, Path.Combine(root, "installation.json"), true);
                    using var directory = new SafeDirectory(root);
                    directory.Flush();
                }
                else RestoreActivation.Commit(root, old);
            }
            receipt.Advance(RestorePhase.Aborted).Save(root);
            terminal.Write("Restore aborted before writer cutoff. Prior authority retained; services remain stopped.");
            return 0;
        }
        throw new UsageException("Restore resume reconciliation has not yet been implemented.");
    }
}
