<Project>
  <PropertyGroup>
    <WayfarerVersion>1.4.1</WayfarerVersion>
    <Version>$(WayfarerVersion)</Version>
    <PackageVersion>$(WayfarerVersion)</PackageVersion>
    <AssemblyInformationalVersion>$(WayfarerVersion)</AssemblyInformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
</Project>
